<?php

// src/UserBundle/Service/FileUploader.php

namespace UserBundle\Service;

use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class FileUploader {

    private $targetDirectory;

    public function __construct($targetDirectory) {
        $this->targetDirectory = $targetDirectory;
    }

    public function upload(UploadedFile $file) {
        
         $filetype = $file['filetype'];

        $type = strchr($filetype, "/");

        $typeImage = str_replace("/", "", $type);


        $fileName = $this->generateUniqueFileName() . '.' . $typeImage;

        
        
        
        //$fileName = md5(uniqid()) . '.' . $file->guessExtension();

        try {
            $file->move($this->getTargetDirectory(), $fileName);
        } catch (FileException $e) {
            // ... handle exception if something happens during file upload
        }

        return $fileName;
    }

    public function getTargetDirectory() {
        return $this->targetDirectory;
    }
    
    /**
     * @return string
     */
    private function generateUniqueFileName() {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

}
