<?php

namespace AppBundle\Repository;

/**
 * TracheAgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrancheAgeRepository extends \Doctrine\ORM\EntityRepository
{
}
