#user:
#    resource: "@UserBundle/Controller/"
#    type:     rest
#    prefix:   /api
#    defaults:
#        _format: json

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
user:
    resource: '@UserBundle/Controller/'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


api_login_check:
    path: /api/login_check
    
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc