<?php

namespace UserBundle\Repository;

/**
 * FocusGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FocusGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
