<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'nelmio_api_doc.formatter.swagger_formatter' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Formatter/SwaggerFormatter.php';

$this->services['nelmio_api_doc.formatter.swagger_formatter'] = $instance = new \Nelmio\ApiDocBundle\Formatter\SwaggerFormatter('dot_notation');

$instance->setBasePath('/api');
$instance->setApiVersion('0.1');
$instance->setSwaggerVersion('1.2');
$instance->setInfo($this->parameters['nelmio_api_doc.swagger.info']);

return $instance;
