<?php

/* Copyright (C) 2016 OUICARE, All Rights Reserved.
 * Web site : www.ouicare.net
 *
 *  __       .  __  __   __  __
 * /  \ |  | | /   /  | |   |__|
 * \__/ |__| | \__ \__| |   |__
 *
 *
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * This file can not be copied and/or distributed without the express permission of OUICARE
 *
 * @author Mohamed Amine <Mohamed.ABBADI@ouicare.net>, 28/06/2016
 */

namespace UserBundle\Controller\Api;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use UserBundle\Entity\Media;
use Nelmio\ApiDocBundle\Annotation\ApiDoc;

/**
 * Admin Controller
 * @author zouaghui jamel
 */
class UserController extends Controller {

    /**
     * @ApiDoc(
     *     resource=true,
     *     description="Get the list of all users",
     *     section="users"
     * )
     *
     * @Route("/api/users",name="list_users")
     * @Method({"GET"})
     */
    public function listUsers() {

        $users = $this->getDoctrine()->getRepository('UserBundle:User')->findAll();

        if (!count($users)) {
            $response = array(
                'code' => 1,
                'message' => 'No users found!',
                'errors' => null,
                'result' => null
            );


            return new JsonResponse($response, Response::HTTP_NOT_FOUND);
        }


        $data = $this->get('jms_serializer')->serialize($users, 'json');
  

        $response = array(
            'code' => 0,
            'message' => 'success',
            'errors' => null,
            'result' => json_decode($data)
        );

        return new JsonResponse($response, 200);
    }

    /**
     * @ApiDoc(
     * description="Create a new user",
     *
     *    statusCodes = {
     *        201 = "Creation with success",
     *        400 = "invalid form"
     *    },
     *    responseMap={
     *         201 = {"class"=User::class},
     *
     *    },
     *     section="users"
     *
     *
     * )
     *
     * @param Request $request
     * @return JsonResponse
     * @Route("/api/users/addnew",name="new_user")
     * @Method({"POST"})
     */
    public function createUser(Request $request) {
        $em = $this->getDoctrine()->getManager();
       
        $media = new Media();


        $file = $request->files->get('image');
        $data= json_decode($request->request->get('formModel'));
    
        if ($file) {
            $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();
            try {
                $file->move($this->getParameter('users_directory'), $fileName);
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }

            $media->setName($fileName);
            
        }
       
        $entity = $this->get('jms_serializer')->deserialize(json_encode($data), 'UserBundle\Entity\User', 'json');
        
       
        $entity->setPhoto($media);
        $entity->setEnabled('0');
        $entity->setMobilePhone($data->mobilePhone);

        $em->persist($entity);
        $em->flush();
        $response = array(
            'code' => 0,
            'message' => 'User created!',
            'errors' => null,
            'result' => null
        );

        return new JsonResponse($response, Response::HTTP_CREATED);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName() {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @ApiDoc(
     *     resource=true,
     *     description="Get the user by username",
     *     section="users"
     * )
     *
     * @Route("/api/user/{username}",name="show_user_connected")
     * @Method({"GET"})
     */
    public function showUserByUsername(Request $request, $username) {

        $user = $this->getDoctrine()->getRepository('UserBundle:User')->findBy(array('username' => $username));

        if (!count($user)) {
            $response = array(
                'code' => 1,
                'message' => 'No user connected found!',
                'errors' => null,
                'result' => null
            );


            return new JsonResponse($response, Response::HTTP_NOT_FOUND);
        }


        $data = $this->get('jms_serializer')->serialize($user, 'json');

        $response = array(
            'code' => 0,
            'message' => 'success',
            'errors' => null,
            'result' => json_decode($data)
        );

        return new JsonResponse($response, 200);
    }

    /**
     * @ApiDoc(
     * description="Create a media",
     *
     *    statusCodes = {
     *        201 = "Creation with success",
     *        400 = "invalid form"
     *    },
     *    responseMap={
     *         201 = {"class"=Media::class},
     *
     *    },
     *     section="users"
     *
     *
     * )
     *
     * @param Request $request
     * @return JsonResponse
     * @Route("/api/users/addmedia",name="new_media")
     * @Method({"POST"})
     */
    public function createMedia(Request $request) {

        $em = $this->getDoctrine()->getManager();
        //$user = $this->getUser();
        $user = $this->getDoctrine()->getRepository('UserBundle:User')->find($this->getUser()->getId());

        $entity = new Media();


        $file = $request->files->get('image');
        if ($file) {
            $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();
            try {
                $file->move($this->getParameter('users_directory'), $fileName);
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }

            $entity->setName($fileName);
            
        }
        $user->setPhoto($entity);
       
        $em->flush();

        $response = array(
            'code' => 0,
            'message' => 'User created!',
            'errors' => null,
            'result' => null
        );

        return new JsonResponse($response, Response::HTTP_CREATED);
    }

}
