<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZvx56xy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZvx56xy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZvx56xy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZvx56xy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZvx56xy\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Zvx56xy',
    'container.build_id' => '42781374',
    'container.build_time' => 1555921151,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZvx56xy');
